name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGUxMThlM2ItZjBhNC00MjJmLTk0ZjQtZGM4NTY5ODEzNmNiIiwidGVuYW50X2lkIjoiYzY1NTE0NDM0MDhhYmM4ZjczZGVmMmNlZWQ1MzU4NmY4MGYxZjE4MDI1YTQ3NjA5Y2MwNmI4YjU4NDQwMTI0OSIsImludGVybmFsX3NlY3JldCI6IjIzZjE4YTAyLTk4MDMtNDAyMy05OTY2LTk1NzhmNzUyNWZjMCJ9.s5YSI2SB40bqFOxtZumtFDZ5fQkUdbDRPA11Go6fHTI"

JWT_SCERET = "SULTAN"
